import "dotenv/config";
import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import crypto from "crypto";
import fetch from "node-fetch";
import { createRemoteJWKSet, jwtVerify } from "jose";

const app = express();
app.disable("x-powered-by");

// Blackboard LTI 1.3 uses OIDC with form_post
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/* =========================================================
   ENV
========================================================= */
const TOOL_BASE_URL = (
  process.env.TOOL_BASE_URL || "https://widget-integ.onrender.com"
).trim();
const LEARN_HOST = (
  process.env.LEARN_HOST || "https://mapua-test.blackboard.com"
).trim();

// Tool registration values (set after Dev Portal + Learn admin)
const LTI_CLIENT_ID = (process.env.LTI_CLIENT_ID || "").trim(); // Client ID used by platform (your tool)
const LTI_DEPLOYMENT_ID = (process.env.LTI_DEPLOYMENT_ID || "").trim(); // optional but recommended

// Platform values (from Learn / LTI settings)
const PLATFORM_ISSUER = (process.env.PLATFORM_ISSUER || "").trim();
const PLATFORM_JWKS_URL = (process.env.PLATFORM_JWKS_URL || "").trim();
const PLATFORM_OIDC_AUTH_ENDPOINT = (
  process.env.PLATFORM_OIDC_AUTH_ENDPOINT || ""
).trim();

// REST application key/secret for 3LO (from Learn Admin -> REST API Integrations)
const REST_KEY = (process.env.REST_KEY || "").trim();
const REST_SECRET = (process.env.REST_SECRET || "").trim();

// Tool JWKS (public) to expose for registration (generated by you)
const TOOL_PUBLIC_JWKS_JSON = (process.env.TOOL_PUBLIC_JWKS_JSON || "").trim();

// 3LO scope
const OAUTH_SCOPE = (process.env.OAUTH_SCOPE || "read").trim();

/* =========================================================
   STATE / NONCE STORE (IN-MEMORY)
   - Works fine for a single Render instance.
   - If you scale horizontally, use Redis/etc.
========================================================= */
const STATE_TTL_MS = 10 * 60 * 1000; // 10 minutes
const stateStore = new Map();

function now() {
  return Date.now();
}
function randId(bytes = 16) {
  return crypto.randomBytes(bytes).toString("hex");
}
function putState(state, nonce) {
  stateStore.set(state, { nonce, createdAt: now() });
}
function popState(state) {
  const v = stateStore.get(state);
  if (v) stateStore.delete(state);
  return v || null;
}
function cleanupStates() {
  const t = now();
  for (const [k, v] of stateStore.entries()) {
    if (t - v.createdAt > STATE_TTL_MS) stateStore.delete(k);
  }
}
setInterval(cleanupStates, 60 * 1000).unref();

/* =========================================================
   HEADERS (ALLOW BLACKBOARD TO IFRAME YOUR TOOL)
========================================================= */
app.use((req, res, next) => {
  // Allow Blackboard Learn Ultra to frame your pages
  res.setHeader(
    "Content-Security-Policy",
    `frame-ancestors ${LEARN_HOST} https://*.blackboard.com;`
  );
  next();
});

/* =========================================================
   STATIC
========================================================= */
app.use(express.static(path.join(__dirname, "public"), { etag: true }));

/* =========================================================
   ROUTES
========================================================= */
app.get("/health", (req, res) => {
  res.json({
    ok: true,
    service: "mapua-uef-widget",
    time: new Date().toISOString(),
  });
});

/**
 * Tool JWKS URL (paste into Dev Portal LTI 1.3 config as "Tool JWKS URL")
 */
app.get("/.well-known/jwks.json", (req, res) => {
  if (!TOOL_PUBLIC_JWKS_JSON) {
    return res
      .status(500)
      .json({ error: "Missing TOOL_PUBLIC_JWKS_JSON env var" });
  }
  res.type("application/json").send(TOOL_PUBLIC_JWKS_JSON);
});

/* =========================================================
   LTI 1.3: OIDC Login Initiation Endpoint
   Dev Portal "Login Initiation URL" => https://widget-integ.onrender.com/lti/login
========================================================= */
app.get("/lti/login", async (req, res) => {
  try {
    // Per LTI 1.3 OIDC flow, platform sends these (commonly as query params)
    const iss = String(req.query.iss || "").trim();
    const login_hint = String(req.query.login_hint || "").trim();
    const target_link_uri = String(req.query.target_link_uri || "").trim();
    const lti_message_hint = String(req.query.lti_message_hint || "").trim();
    const client_id_from_platform = String(req.query.client_id || "").trim();

    if (!iss || !login_hint || !target_link_uri) {
      return res
        .status(400)
        .send(
          "Missing required OIDC login params (iss, login_hint, target_link_uri)"
        );
    }

    // Sanity checks on server config
    if (!PLATFORM_OIDC_AUTH_ENDPOINT || !PLATFORM_ISSUER) {
      return res
        .status(500)
        .send(
          "Missing PLATFORM_OIDC_AUTH_ENDPOINT / PLATFORM_ISSUER (set after Learn tool registration)"
        );
    }

    // Optional: enforce issuer match (recommended)
    if (PLATFORM_ISSUER && iss !== PLATFORM_ISSUER) {
      return res.status(400).send(`Issuer mismatch. Got iss=${iss}`);
    }

    // Determine which client_id to use for the auth request
    const client_id = client_id_from_platform || LTI_CLIENT_ID;
    if (!client_id) {
      return res
        .status(500)
        .send("Missing LTI_CLIENT_ID (and platform did not send client_id)");
    }

    // Launch endpoint (Tool Redirect URL) must match what you registered
    // Prefer what platform asked for if it's on our domain; else fallback to TOOL_BASE_URL launch.
    let redirectUri = `${TOOL_BASE_URL}/lti/launch`;
    if (target_link_uri && target_link_uri.startsWith(TOOL_BASE_URL)) {
      redirectUri = target_link_uri;
    }

    // Create state + nonce for CSRF / replay protections
    const state = `st_${randId(16)}`;
    const nonce = `no_${randId(16)}`;
    putState(state, nonce);

    // Build OIDC Authentication Request to the platform
    const params = new URLSearchParams({
      scope: "openid",
      response_type: "id_token",
      response_mode: "form_post",
      prompt: "none",
      client_id,
      redirect_uri: redirectUri,
      state,
      nonce,
      login_hint,
    });

    // lti_message_hint is optional but MUST be echoed back unmodified if present
    if (lti_message_hint) params.set("lti_message_hint", lti_message_hint);

    const authUrl = `${PLATFORM_OIDC_AUTH_ENDPOINT}?${params.toString()}`;
    return res.redirect(authUrl);
  } catch (err) {
    console.error("OIDC login initiation error:", err);
    return res.status(500).send("OIDC login initiation failed");
  }
});

/* =========================================================
   LTI 1.3: Launch / Redirect Endpoint (form_post)
   Dev Portal "Tool Redirect URL(s)" => https://widget-integ.onrender.com/lti/launch
========================================================= */
app.post("/lti/launch", async (req, res) => {
  try {
    const id_token = String(req.body.id_token || "").trim();
    const state = String(req.body.state || "").trim();

    if (!id_token) return res.status(400).send("Missing id_token");
    if (!state) return res.status(400).send("Missing state");

    // Ensure we have the platform details
    if (!PLATFORM_JWKS_URL || !PLATFORM_ISSUER) {
      return res
        .status(500)
        .send(
          "Missing PLATFORM_JWKS_URL / PLATFORM_ISSUER (set after Learn tool registration)"
        );
    }
    if (!LTI_CLIENT_ID) {
      return res
        .status(500)
        .send("Missing LTI_CLIENT_ID (set after Learn tool registration)");
    }

    // Validate state -> nonce
    const st = popState(state);
    if (!st) return res.status(400).send("Invalid/expired state");

    // Verify id_token signature + iss + aud
    const JWKS = createRemoteJWKSet(new URL(PLATFORM_JWKS_URL));
    const { payload } = await jwtVerify(id_token, JWKS, {
      issuer: PLATFORM_ISSUER,
      audience: LTI_CLIENT_ID,
    });

    // Validate nonce matches what we stored for this state
    const nonce = String(payload.nonce || "");
    if (!nonce || nonce !== st.nonce) {
      return res.status(400).send("Nonce mismatch");
    }

    // Optional: validate deployment_id if you set it
    const deploymentId =
      payload["https://purl.imsglobal.org/spec/lti/claim/deployment_id"];
    if (LTI_DEPLOYMENT_ID && deploymentId !== LTI_DEPLOYMENT_ID) {
      return res.status(400).send("deployment_id mismatch");
    }

    // Blackboard one-time session token (iframe-safe 3LO)
    const oneTime =
      payload["https://blackboard.com/lti/claim/one_time_session_token"];
    if (!oneTime) {
      return res.status(400).send("Missing one_time_session_token LTI claim");
    }

    // Start Learn 3LO authorization code flow using one_time_session_token
    // Requires REST_KEY (client_id) for the REST API integration.
    if (!REST_KEY) {
      return res
        .status(500)
        .send(
          "Missing REST_KEY (create REST API Integration in Learn and set env vars)"
        );
    }

    const oauthRedirectUri = `${TOOL_BASE_URL}/oauth/callback`;
    const oauthParams = new URLSearchParams({
      redirect_uri: oauthRedirectUri,
      response_type: "code",
      client_id: REST_KEY,
      scope: OAUTH_SCOPE,
      state: `oauth_${randId(12)}`,
      one_time_session_token: String(oneTime),
    });

    // Blackboard 3LO authorize endpoint
    const authUrl = `${LEARN_HOST}/learn/api/public/v1/oauth2/authorizationcode?${oauthParams.toString()}`;
    return res.redirect(authUrl);
  } catch (err) {
    console.error("LTI launch error:", err);
    return res.status(401).send("LTI launch failed");
  }
});

/* =========================================================
   3LO CALLBACK: Exchange code -> access_token
   Learn redirects here after /authorizationcode
========================================================= */
app.get("/oauth/callback", async (req, res) => {
  try {
    const code = String(req.query.code || "").trim();
    if (!code) return res.status(400).send("Missing code");

    if (!REST_KEY || !REST_SECRET) {
      return res.status(500).send("Missing REST_KEY/REST_SECRET env vars");
    }

    const redirectUri = `${TOOL_BASE_URL}/oauth/callback`;
    const tokenUrl = `${LEARN_HOST}/learn/api/public/v1/oauth2/token?code=${encodeURIComponent(
      code
    )}&redirect_uri=${encodeURIComponent(redirectUri)}`;

    const basic = Buffer.from(`${REST_KEY}:${REST_SECRET}`).toString("base64");

    const r = await fetch(tokenUrl, {
      method: "POST",
      headers: {
        Authorization: `Basic ${basic}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: "grant_type=authorization_code",
    });

    if (!r.ok) {
      const txt = await r.text();
      console.error("3LO token exchange failed:", r.status, txt);
      return res.status(500).send("3LO token exchange failed");
    }

    const data = await r.json();
    const accessToken = data.access_token;
    if (!accessToken)
      return res.status(500).send("Missing access_token from Learn");

    // Redirect to the UEF boot page to store token + load uef.js
    return res.redirect(
      `/uef-boot.html?token=${encodeURIComponent(accessToken)}`
    );
  } catch (err) {
    console.error("OAuth callback error:", err);
    return res.status(500).send("OAuth callback failed");
  }
});

/* =========================================================
   LISTEN
========================================================= */
const PORT = Number(process.env.PORT || 10000);
app.listen(PORT, "0.0.0.0", () => {
  console.log(`Listening on http://0.0.0.0:${PORT}`);
  console.log("TOOL_BASE_URL =", TOOL_BASE_URL);
  console.log("LEARN_HOST     =", LEARN_HOST);
});
